// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399

import type * as components from "./components";
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    HCopy: typeof components.HCopy;
  }
}
export {};

